name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        type: choice
        options:
          - smoke
          - regression
  schedule:
    - cron: '10 8 * * *'

jobs:

  test:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
        # Execute Smoke tests in the solution
    - name: Execute Smoke tests
      if: "github.event.inputs.deployment_target == 'smoke' || github.event.schedule == '10 8 * * *'"
      run: dotnet test --filter Category=Smoke

        # Execute Regression tests in the solution
    - name: Execute Regression tests
      if: "github.event.inputs.deployment_target == 'regression'"
      run: dotnet test --filter Category=Regression
      
    - name: Execute tests
      if: "github.event.inputs.deployment_target != 'regression' && github.event.inputs.deployment_target != 'smoke'"
      run: dotnet test

    - name: Load test report history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
         gh_pages: gh-pages
         allure_history: allure-history
         allure_results: GraduateWork/bin/Debug/net8.0/allure-results

    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
